In [6]:
import numpy as np
import pandas as pd
import nltk
import matplotlib.pyplot as plt
from nltk.tokenize import word_tokenize

In [7]:
nltk.download('punkt')
s = "This is very good mov"
print(word_tokenize(s))

# using split 
lens = [w for w in s.split()]
print(lens)

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
['This', 'is', 'very', 'good', 'mov']
['This', 'is', 'very', 'good', 'mov']


In [8]:
nltk.download('stopwords')
from nltk.corpus import stopwords

words = stopwords.words('english')
print(words)
stop = np.array(words)
print(stop.shape)

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
['i', 'me', 'my', 'myself', 'we', 'our', 'ours', 'ourselves', 'you', "you're", "you've", "you'll", "you'd", 'your', 'yours', 'yourself', 'yourselves', 'he', 'him', 'his', 'himself', 'she', "she's", 'her', 'hers', 'herself', 'it', "it's", 'its', 'itself', 'they', 'them', 'their', 'theirs', 'themselves', 'what', 'which', 'who', 'whom', 'this', 'that', "that'll", 'these', 'those', 'am', 'is', 'are', 'was', 'were', 'be', 'been', 'being', 'have', 'has', 'had', 'having', 'do', 'does', 'did', 'doing', 'a', 'an', 'the', 'and', 'but', 'if', 'or', 'because', 'as', 'until', 'while', 'of', 'at', 'by', 'for', 'with', 'about', 'against', 'between', 'into', 'through', 'during', 'before', 'after', 'above', 'below', 'to', 'from', 'up', 'down', 'in', 'out', 'on', 'off', 'over', 'under', 'again', 'further', 'then', 'once', 'here', 'there', 'when', 'where', 'why', 'how', 'all', 'any', 'bo

In [9]:
len = [w for w in lens if w not in stop]
print(len)


['This', 'good', 'mov']


In [10]:
### stemming
from nltk.stem import PorterStemmer

ps = PorterStemmer()
stemmed = [ps.stem(w) for w in len]

print(stemmed)


['thi', 'good', 'mov']


In [11]:
#  data loading

train = pd.read_csv('https://raw.githubusercontent.com/dD2405/Twitter_Sentiment_Analysis/master/train.csv')

train

id  label                                              tweet
0          1      0   @user when a father is dysfunctional and is s...
1          2      0  @user @user thanks for #lyft credit i can't us...
2          3      0                                bihday your majesty
3          4      0  #model   i love u take with u all the time in ...
4          5      0             factsguide: society now    #motivation
...      ...    ...                                                ...
31957  31958      0  ate @user isz that youuu?😍😍😍😍😍ð...
31958  31959      0    to see nina turner on the airwaves trying to...
31959  31960      0  listening to sad songs on a monday morning otw...
31960  31961      1  @user #sikh #temple vandalised in in #calgary,...
31961  31962      0                   thank you @user for you follow  

[31962 rows x 3 columns]

In [12]:
test = pd.read_csv('https://raw.githubusercontent.com/dD2405/Twitter_Sentiment_Analysis/master/test.csv')

test.head(10)

id                                              tweet
0  31963  #studiolife #aislife #requires #passion #dedic...
1  31964   @user #white #supremacists want everyone to s...
2  31965  safe ways to heal your #acne!!    #altwaystohe...
3  31966  is the hp and the cursed child book up for res...
4  31967    3rd #bihday to my amazing, hilarious #nephew...
5  31968                        choose to be   :) #momtips 
6  31969  something inside me dies 💦💿✨  eyes nes...
7  31970  #finished#tattoo#inked#ink#loveit❤️ #❤ï¸...
8  31971   @user @user @user i will never understand why...
9  31972  #delicious   #food #lovelife #capetown mannaep...

In [13]:
# cleaning words
# using regular expression
import re
  

In [14]:
def remove_pattern(pattern, text):
  occur = re.findall(pattern, text)
  for i in occur:
    text = re.sub(i, "", text)

  return text

In [15]:
pat = "@[\w]*"
train['new_tweet'] = [remove_pattern(pat, sen) for sen in train['tweet']]


print(train.info())

print(train['new_tweet'])

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 31962 entries, 0 to 31961
Data columns (total 4 columns):
 #   Column     Non-Null Count  Dtype 
---  ------     --------------  ----- 
 0   id         31962 non-null  int64 
 1   label      31962 non-null  int64 
 2   tweet      31962 non-null  object
 3   new_tweet  31962 non-null  object
dtypes: int64(2), object(2)
memory usage: 998.9+ KB
None
0          when a father is dysfunctional and is so sel...
1          thanks for #lyft credit i can't use cause th...
2                                      bihday your majesty
3        #model   i love u take with u all the time in ...
4                   factsguide: society now    #motivation
                               ...                        
31957    ate  isz that youuu?😍😍😍😍😍😍ðŸ...
31958      to see nina turner on the airwaves trying to...
31959    listening to sad songs on a monday morning otw...
31960     #sikh #temple vandalised in in #calgary, #wso...
31961      

In [16]:
#  remove !

train['new_tweet'] = train['new_tweet'].str.replace("^a-zA-Z#", " ")

print(train['new_tweet'])

0          when a father is dysfunctional and is so sel...
1          thanks for #lyft credit i can't use cause th...
2                                      bihday your majesty
3        #model   i love u take with u all the time in ...
4                   factsguide: society now    #motivation
                               ...                        
31957    ate  isz that youuu?😍😍😍😍😍😍ðŸ...
31958      to see nina turner on the airwaves trying to...
31959    listening to sad songs on a monday morning otw...
31960     #sikh #temple vandalised in in #calgary, #wso...
31961                          thank you  for you follow  
Name: new_tweet, Length: 31962, dtype: object


In [17]:
# tokenization using split

train['new_tweet'] = train['new_tweet'].apply(lambda x : x.split())

print(train['new_tweet'])

0        [when, a, father, is, dysfunctional, and, is, ...
1        [thanks, for, #lyft, credit, i, can't, use, ca...
2                                  [bihday, your, majesty]
3        [#model, i, love, u, take, with, u, all, the, ...
4                 [factsguide:, society, now, #motivation]
                               ...                        
31957    [ate, isz, that, youuu?😍😍😍😍😍ðŸ˜...
31958    [to, see, nina, turner, on, the, airwaves, try...
31959    [listening, to, sad, songs, on, a, monday, mor...
31960    [#sikh, #temple, vandalised, in, in, #calgary,...
31961                       [thank, you, for, you, follow]
Name: new_tweet, Length: 31962, dtype: object


In [18]:
# stopword removal
train['new_tweet'] = train['new_tweet'].apply(lambda x : [w for w in x if w not in stop])

print(train['new_tweet'])

0        [father, dysfunctional, selfish, drags, kids, ...
1        [thanks, #lyft, credit, can't, use, cause, off...
2                                        [bihday, majesty]
3        [#model, love, u, take, u, time, ur📱!!!, ðŸ...
4                      [factsguide:, society, #motivation]
                               ...                        
31957    [ate, isz, youuu?😍😍😍😍😍😍😍ð...
31958    [see, nina, turner, airwaves, trying, wrap, ma...
31959    [listening, sad, songs, monday, morning, otw, ...
31960    [#sikh, #temple, vandalised, #calgary,, #wso, ...
31961                                      [thank, follow]
Name: new_tweet, Length: 31962, dtype: object


In [19]:
# lametization
train['new_tweet'] = train['new_tweet'].apply(lambda x : [ps.stem(w) for w in x])

train['new_tweet'] = train['new_tweet'].apply(lambda x : ' '.join(x))

print(train['new_tweet'])

0        father dysfunct selfish drag kid dysfunction. ...
1        thank #lyft credit can't use caus offer wheelc...
2                                           bihday majesti
3        #model love u take u time ur📱!!! 😙😎ðŸ...
4                               factsguide: societi #motiv
                               ...                        
31957    ate isz youuu?😍😍😍😍😍😍😍😍...
31958    see nina turner airwav tri wrap mantl genuin h...
31959             listen sad song monday morn otw work sad
31960     #sikh #templ vandalis #calgary, #wso condemn act
31961                                         thank follow
Name: new_tweet, Length: 31962, dtype: object


In [ ]:
# apply count vectorizer

from sklearn.feature_extraction.text import CountVectorizer

vec = CountVectorizer(max_df = 0.8, min_df = 2, max_features= 1000, stop_words= 'english')
f_data = vec.fit_transform(train['new_tweet'])


pdf_data = pd.DataFrame(f_data.todense())

pdf_data

#  apply tfidf vectorizer





0    1    2    3    4    5    6    ...  993  994  995  996  997  998  999
0        0    0    0    0    0    0    0  ...    0    0    0    0    0    0    0
1        0    0    0    0    0    0    0  ...    0    0    0    0    0    0    0
2        0    0    0    0    0    0    0  ...    0    0    0    0    0    0    0
3        0    0    0    0    0    0    0  ...    0    0    0    0    0    0    0
4        0    0    0    0    0    0    0  ...    0    0    0    0    0    0    0
...    ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...
31957    0    0    0    0    0    0    0  ...    0    0    0    0    0    0    0
31958    0    0    0    0    0    0    0  ...    0    0    0    0    0    0    0
31959    0    0    0    0    0    0    0  ...    0    0    0    0    0    0    0
31960    0    0    0    0    0    0    0  ...    0    0    0    0    0    0    0
31961    0    0    0    0    0    0    0  ...    0    0    0    0    0    0    0

[31962 rows x 1000 columns]

In [ ]:
# train test split

from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(pdf_data, train['label'], test_size = 0.3)


In [ ]:
# model
# LogisticRegression
from sklearn.linear_model import LogisticRegression

LR = LogisticRegression(solver = 'lbfgs')

LR.fit(x_train, y_train)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=None, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [ ]:
# prediction

prediction = LR.predict(x_test)

prediction


array([0, 0, 0, ..., 0, 0, 0])

In [ ]:
# accuracy
from sklearn.metrics import accuracy_score

acc = accuracy_score(prediction, y_test)

print(acc)


0.9468140577745333


In [ ]:
# f1 score

from sklearn.metrics import f1_score

acc = f1_score(prediction, y_test)

print(acc)

0.48588709677419356


In [ ]:
# using svm

from sklearn.svm import SVC

sv = SVC()

sv.fit(x_train, y_train)

SVC(C=1.0, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='scale', kernel='rbf',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)

In [23]:
# prediction using svm
prediction = sv.predict(x_test)

prediction

array([0, 0, 0, ..., 0, 0, 0])

In [26]:
from sklearn.metrics import accuracy_score

acc = accuracy_score(prediction, y_test)
print(acc)

from sklearn.metrics import f1_score

acc_f1 = f1_score(prediction, y_test)
print(acc_f1)

0.9528626551256648
0.5349794238683128


In [20]:
# Generating tf-idf vector
from sklearn.feature_extraction.text import TfidfVectorizer

#  paas parameter otherwise it will crash
vectorizer = TfidfVectorizer(max_df = 0.8, min_df = 2, max_features= 1000, stop_words= 'english');

data_tfidf = vectorizer.fit_transform(train['new_tweet'])

data_tfidf = pd.DataFrame(data_tfidf.todense())

data_tfidf


0    1    2    3    4    5    6    ...  993  994  995  996  997  998  999
0      0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0
1      0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0
2      0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0
3      0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0
4      0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0
...    ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...
31957  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0
31958  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0
31959  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0
31960  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0
31961  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0

[31962 rows x 1000 columns]

In [21]:
#  train test split
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(data_tfidf, train['label'], test_size = 0.3)


In [22]:
# LogisticRegression on tfidf
from sklearn.linear_model import LogisticRegression

LR = LogisticRegression(solver = 'lbfgs')

LR.fit(x_train, y_train)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=None, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [23]:
# prediction

prediction = LR.predict(x_test)

prediction


array([0, 0, 0, ..., 0, 0, 0])

In [24]:
# accuracy
from sklearn.metrics import accuracy_score

acc = accuracy_score(prediction, y_test)

print(acc)


0.9505683595786839


In [25]:
# f1 score

from sklearn.metrics import f1_score

acc = f1_score(prediction, y_test)

print(acc)

0.5021008403361344


In [26]:
# using svm on tfidf

from sklearn.svm import SVC

sv = SVC()

sv.fit(x_train, y_train)

SVC(C=1.0, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='scale', kernel='rbf',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)

In [27]:
# prediction using svm
prediction = sv.predict(x_test)

prediction

array([0, 0, 0, ..., 0, 0, 0])

In [28]:
from sklearn.metrics import accuracy_score

acc = accuracy_score(prediction, y_test)
print(acc)

from sklearn.metrics import f1_score

acc_f1 = f1_score(prediction, y_test)
print(acc_f1)

0.9530712274481177
0.5417515274949083
